version: '3.3'

networks:
  poll:
    driver: bridge
    ipam:
      config:
        - subnet: 174.20.0.1/16

services:
  db:
    image: postgres   
    # volumes:
    #   - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: FiGreo32reoqowR1321e12
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      poll:
        ipv4_address: 174.20.0.4

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      poll:
        ipv4_address: 174.20.0.5

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - 4000:4000
    networks:
        poll:
          ipv4_address: 174.20.0.3

  frontend:
    build: ./frontend
    depends_on:
     - backend
    ports: 
     - 5000:5000
    networks:
      poll:
        ipv4_address: 174.20.0.6


  